name = "outlook-email-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"

rules = [
  { type = "Text", globs = ["**/*.html"], fallthrough = false }
]

[triggers]
crons = ["0 */6 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "outlook-emails"
database_id = "039e1bfb-98b2-4157-a041-8e68c4b56626"
